version: '3'
services:
  nginx:
    image: nginx:latest
    ports:
      - 8090:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./www:/var/www/
    depends_on:
      - php

  php:
    container_name: php-laravel
    build: ./php
    volumes:
      - ./www:/var/www/

  db:
    build: ./mysql
    volumes:
      - ./mysql/data/:/var/lib/mysql
    ports:
      - 3306:3306

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - 8888:80
    depends_on:
      - db
